//   Copyright 2017 Wercker Holding BV
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"sort"
	"strings"

	"github.com/golang/protobuf/proto"
	"github.com/golang/protobuf/protoc-gen-go/descriptor"
	plugin "github.com/golang/protobuf/protoc-gen-go/plugin"
)

const typescriptFileHeader = `/* eslint-disable */
// ------------------------------------
// Code generated by protoc-gen-typescript
// source: {{.GetName}}
// THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT!
// ------------------------------------

export type StatusObject = {
  code: number;
  details: string;
  metadata: any;
};

export type ServiceError = StatusObject & Error;
`

// Map qualified name to Message
var messageMap map[string]*Message

// Map qualified name to Enum
var enumMap map[string]*Enum

func init() {
	messageMap = make(map[string]*Message)
	enumMap = make(map[string]*Enum)
}

type typeEntry struct {
	name   string
	output string
}

// shouldEmitFile returns true if types from this proto file should be included
// in the output. We exclude google/protobuf/* files (descriptor types that vary
// by protoc version) except wrappers.proto which application fields reference.
func shouldEmitFile(filename string) bool {
	if filename == "google/protobuf/wrappers.proto" {
		return true
	}
	if strings.HasPrefix(filename, "google/protobuf/") {
		return false
	}
	return true
}

func main() {
	data, err := ioutil.ReadAll(os.Stdin)
	if err != nil {
		log.Fatal(err)
	}

	var req plugin.CodeGeneratorRequest
	if err := proto.Unmarshal(data, &req); err != nil {
		log.Fatalf("unable to parse protobuf: %v", err)
	}

	// Phase 1: Register all types from all files into messageMap/enumMap
	// so that type references (e.g. google.protobuf.BoolValue) resolve correctly.
	for _, f := range req.ProtoFile {
		ns := strings.Replace(*f.Package, ".", "$", -1) + "$"
		for _, enum := range f.EnumType {
			registerEnumType(ns, enum)
		}
		for _, msg := range f.MessageType {
			registerMessageType(ns, msg)
		}
	}

	// Phase 2: Collect type entries only from non-excluded files.
	var entries []typeEntry
	for _, f := range req.ProtoFile {
		if !shouldEmitFile(f.GetName()) {
			continue
		}
		ns := strings.Replace(*f.Package, ".", "$", -1) + "$"
		for _, enum := range f.EnumType {
			entries = append(entries, collectEnumEntries(ns, enum)...)
		}
		for _, msg := range f.MessageType {
			entries = append(entries, collectMessageEntries(ns, msg)...)
		}
		for _, svc := range f.Service {
			entries = append(entries, collectServiceEntries(ns, svc)...)
		}
	}

	// Sort all entries alphabetically by type name for deterministic output.
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].name < entries[j].name
	})

	// Write header + sorted entries.
	code := bytes.NewBuffer(nil)
	code.WriteString(typescriptFileHeader)
	for _, e := range entries {
		code.WriteString(e.output)
	}

	const outputFilename = "index.ts"

	emitFiles([]*plugin.CodeGeneratorResponse_File{
		{
			Name:    proto.String(outputFilename),
			Content: proto.String(strings.TrimLeft(code.String(), "\n")),
		},
	})
}

// Phase 1: Register types into maps without generating output.

func registerEnumType(namespace string, enum *descriptor.EnumDescriptorProto) {
	name := namespace + *enum.Name
	e := &Enum{
		Name:   name,
		Values: []string{},
	}
	for _, v := range enum.Value {
		if *v.Number == 0 {
			continue
		}
		e.Values = append(e.Values, *v.Name)
	}
	enumMap[name] = e
}

func registerMessageType(namespace string, msg *descriptor.DescriptorProto) {
	name := namespace + *msg.Name
	m := &Message{
		Name:   name,
		Fields: []*Field{},
		IsMap:  msg.GetOptions().GetMapEntry(),
	}
	nestedNS := name + "$"
	for _, enum := range msg.EnumType {
		registerEnumType(nestedNS, enum)
	}
	for _, nestedType := range msg.NestedType {
		registerMessageType(nestedNS, nestedType)
	}
	for _, field := range msg.Field {
		m.Fields = append(m.Fields, &Field{
			Name: *field.Name,
			Type: getFieldType(name, field),
		})
	}
	messageMap[name] = m
}

// Phase 2: Collect rendered type entries for non-excluded files.

func collectEnumEntries(namespace string, enum *descriptor.EnumDescriptorProto) []typeEntry {
	name := namespace + *enum.Name
	e := enumMap[name]
	var buf bytes.Buffer
	enumTemplate.Execute(&buf, e)
	return []typeEntry{{name: name, output: buf.String()}}
}

func collectMessageEntries(namespace string, msg *descriptor.DescriptorProto) []typeEntry {
	name := namespace + *msg.Name
	m := messageMap[name]

	var entries []typeEntry
	nestedNS := name + "$"
	for _, enum := range msg.EnumType {
		entries = append(entries, collectEnumEntries(nestedNS, enum)...)
	}
	for _, nestedType := range msg.NestedType {
		entries = append(entries, collectMessageEntries(nestedNS, nestedType)...)
	}
	// Map types are inlined, don't emit a separate type
	if !m.IsMap {
		var buf bytes.Buffer
		messageTemplate.Execute(&buf, m)
		entries = append(entries, typeEntry{name: name, output: buf.String()})
	}
	return entries
}

func collectServiceEntries(namespace string, svc *descriptor.ServiceDescriptorProto) []typeEntry {
	name := namespace + *svc.Name
	s := &Service{
		Name:    name,
		Methods: []*Method{},
	}
	for _, method := range svc.Method {
		s.Methods = append(s.Methods, &Method{
			Name:         *method.Name,
			RequestType:  getScopedName(*method.InputType),
			ResponseType: getScopedName(*method.OutputType),
		})
	}
	var buf bytes.Buffer
	serviceTemplate.Execute(&buf, s)
	return []typeEntry{{name: name, output: buf.String()}}
}

func emitFiles(out []*plugin.CodeGeneratorResponse_File) {
	emitResp(&plugin.CodeGeneratorResponse{File: out})
}

func emitResp(resp *plugin.CodeGeneratorResponse) {
	buf, err := proto.Marshal(resp)
	if err != nil {
		log.Fatal(err)
	}
	if _, err := os.Stdout.Write(buf); err != nil {
		log.Fatal(err)
	}
}

func getFieldType(namespace string, field *descriptor.FieldDescriptorProto) string {
	ret := "any" // unknonwn

	switch *field.Type {
	case descriptor.FieldDescriptorProto_TYPE_DOUBLE,
		descriptor.FieldDescriptorProto_TYPE_FLOAT,
		descriptor.FieldDescriptorProto_TYPE_INT32,
		descriptor.FieldDescriptorProto_TYPE_FIXED32,
		descriptor.FieldDescriptorProto_TYPE_UINT32,
		descriptor.FieldDescriptorProto_TYPE_SFIXED32,
		descriptor.FieldDescriptorProto_TYPE_SINT32:
		ret = "number"
	case descriptor.FieldDescriptorProto_TYPE_INT64,
		descriptor.FieldDescriptorProto_TYPE_UINT64,
		descriptor.FieldDescriptorProto_TYPE_FIXED64,
		descriptor.FieldDescriptorProto_TYPE_SFIXED64,
		descriptor.FieldDescriptorProto_TYPE_SINT64:
		// javascript doesn't support 64bit ints
		ret = "string"
	case descriptor.FieldDescriptorProto_TYPE_BOOL:
		ret = "boolean"
	case descriptor.FieldDescriptorProto_TYPE_STRING:
		ret = "string"
	case descriptor.FieldDescriptorProto_TYPE_ENUM:
		name := getScopedName(*field.TypeName)

		_, ok := enumMap[name]
		if !ok {
			panic(fmt.Sprintf("Enum '%v' not found in enum map", name))
		}

		ret = name
	case descriptor.FieldDescriptorProto_TYPE_MESSAGE:
		if *field.TypeName == ".google.protobuf.Timestamp" {
			// Special case for handling timestamps
			ret = "string"
		} else {
			name := getScopedName(*field.TypeName)

			msg, ok := messageMap[name]
			if ok && msg.IsMap {
				keyType := msg.Fields[0].Type
				valueType := msg.Fields[1].Type

				ret = fmt.Sprintf("{ [key: %s]: %s }", keyType, valueType)

				// Maps are represented as an array of map entries. We change the representation to a JS object so
				// we return early to avoid appending array square braces.
				return ret
			}

			ret = name
		}
	case descriptor.FieldDescriptorProto_TYPE_GROUP:
		ret = "any"
	case descriptor.FieldDescriptorProto_TYPE_BYTES:
		ret = "any"
	}
	if *field.Label == descriptor.FieldDescriptorProto_LABEL_REPEATED {
		ret += "[]"
	}

	return ret
}

func getScopedName(origName string) string {
	parts := strings.Split(origName, ".")
	if len(parts) < 2 {
		return "any"
	}

	parts = parts[1:]

	return strings.Join(parts, "$")
}
